mod 'puppetlabs-docker', '4.4.0'
mod 'puppet-nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'samuelson/dockeragent'
mod 'puppetlabs/apt'
mod 'puppetlabs/docker'
